*** Variables ***
${FOOTERPUFFYURL}                                   https://puffy.com/products/puffy-mattress
${FOOTERPUFFYLUXURL}                                https://puffy.com/pages/puffy-lux-mattress
${FOOTERPUFFYROYALURL}                              https://puffy.com/products/puffy-royal-mattress
${FOOTERPUFFYHYBRIDURL}                             https://puffy.com/pages/puffy-hybrid-mattress
${FOOTERCOMFORTERURL}                               https://puffy.com/products/puffy-comforter
${FOOTERMATTRESSPROTECTORURL}                       https://puffy.com/products/puffy-mattress-protector
${FOOTERMATTRESSTOPPERURL}                          https://puffy.com/products/puffy-topper
${FOOTERWEIGHTEDBLANKETURL}                         https://puffy.com/products/puffy-weighted-blanket
${FOOTERDOGBEDURL}                                  https://puffy.com/products/puffy-dog-bed
${FOOTERBEDFRAMEURL}                                https://puffy.com/products/puffy-bed-frame
${FOOTERFOUNDATIONURL}                              https://puffy.com/products/puffy-foundation
${FOOTERADJUSTABLEBASEURL}                          https://puffy.com/products/puffy-adjustable-base
${FOOTERPILLOWURL}                                  https://puffy.com/products/puffy-pillow
${FOOTERBODYPILLOWURL}                              https://puffy.com/products/puffy-body-pillow
${FOOTERMATTRESSPADURL}                             https://puffy.com/products/puffy-mattress-pad
${FOOTERPUFFYBLANKETURL}                            https://puffy.com/products/puffy-blanket
${FOOTERPUFFYSHEETSURL}                             https://puffy.com/products/puffy-sheets
${FOOTERPUFFYRUGURL}                                https://puffy.com/products/puffy-area-rug
${FOOTER101NIGHTSLEEPTRIALURL}                      https://puffy.com/pages/puffy-mattress-sleep-trial
${FOOTERHOWITSMADEURL}                              https://puffy.com/pages/how-its-made
${FOOTERMATTRESSLAYERSURL}                          https://puffy.com/pages/puffy-sleep-system
${FOOTERPERFECTSLEEPURL}                            https://puffy.com/pages/puffy-perfect-sleep
${FOOTERCOMPAREMATTRESSURL}                         https://puffy.com/pages/puffy-mattress-and-puffy-lux
${FOOTERCOMPAREHYBRIDSURL}                          https://puffy.com/pages/compare-hybrid-mattress-puffy-lux-and-royal
${FOOTERPUFFYDONATIONSURL}                          https://puffy.com/pages/puffy-donations-1
${FOOTERAFFILIATEPROGRAMURL}                        https://www.shareasale.com/shareasale.cfm?merchantID=73372
${FOOTERREFERAFRIENDURL}                            https://puffy.com/pages/share?traffic_source=site_footer
${FOOTERMATTRESSAWARDSURL}                          https://puffy.com/pages/top-rated-best-mattress-awards
${FOOTERGIFTSHOPURL}                                https://puffy.com/pages/gift-shop
${FOOTERPUFFYSTOREURL}                              https://puffy.com/collections/puffy-store
${FOOTERPUFFYBLOGURL}                               https://puffy.com/blogs/in-the-clouds
${FOOTERPUFFYREVIEWURL}                             https://www.slumbersearch.com/puffy-mattress-reviews
${FOOTERPUFFYLUXREVIEWURL}                          https://myslumberyard.com/mattress-reviews/puffy-lux-mattress-review/
${FOOTERPUFFYROYALREVIEWURL}                        https://www.oursleepguide.com/mattress/puffy-royal-mattress-review/
${FOOTERPUFFYMATTRESSREVIEWURL}                     https://www.mattressnerd.com/puffy-mattress-review/
${FOOTERREVIEWSURL}                                 https://puffy.com/pages/puffy-mattress-reviews
${FOOTERCONTACTUSURL}                               https://puffy.com/pages/contact-puffy-mattress#contact_us
${FOOTERFAQSURL}                                    https://puffy.com/pages/contact-puffy-mattress
${FOOTERFINANCINGURL}                               https://puffy.com/pages/financing
${FOOTERRETURNPOLICYURL}                            https://puffy.com/pages/return-policy
${FOOTERPUFFYGUARANTEEURL}                          https://puffy.com/pages/puffy-mattress-sleep-guarantee
${FOOTERPRIVACYURL}                                 https://puffy.com/pages/puffy-privacy-policy
${FOOTERTERMSURL}                                   https://puffy.com/pages/terms-and-conditions
${FOOTERWARRANTYURL}                                https://puffy.com/pages/puffy-mattress-warranty
${FOOTERFACEBOOKURL}                                https://www.facebook.com/PuffyMattress/
${FOOTERTWITTERURL}                                 https://twitter.com/puffymattress
${FOOTERINSTAGRAMURL}                               https://www.instagram.com/puffymattress/
${FOOTERYOUTUBEURL}                                 https://www.youtube.com/c/PuffyMattress
${FOOTERLINKEDINURL}                                https://www.linkedin.com/company/puffy
${FOOTERPINTERESTURL}                               https://www.pinterest.com/puffymattressonline/
${FOOTERCOPYRIGHTURL}                               https://puffy.com/
