*** Variables ***
${PDPPUFFYMATTRESSURL}                              https://puffy.com/products/puffy-mattress
${PDPPUFFYLUXMATTRESSURL}                           https://puffy.com/products/puffy-lux-mattress
${HOMEPAGEPUFFYLUXURL}                              https://puffy.com/pages/puffy-lux-mattress
${PDPPUFFYROYALMATTRESSURL}                         https://puffy.com/products/puffy-royal-mattress
${HOMEPAGEPUFFYHYBRIDURL}                           https://puffy.com/pages/puffy-hybrid-mattress
${PDPPUFFYCOMFORTERURL}                             https://puffy.com/products/puffy-comforter
${PDPPUFFYMATTRESSPROTECTORURL}                     https://puffy.com/products/puffy-mattress-protector
${PDPMATTRESSTOPPERURL}                             https://puffy.com/products/puffy-topper
${PDPWEIGHTEDBLANKETURL}                            https://puffy.com/products/puffy-weighted-blanket
${PDPDOGBEDURL}                                     https://puffy.com/products/puffy-dog-bed
${PDPBEDFRAMEURL}                                   https://puffy.com/products/puffy-bed-frame
${PDPFOUNDATIONURL}                                 https://puffy.com/products/puffy-foundation
${PDPADJUSTABLEBASEURL}                             https://puffy.com/products/puffy-adjustable-base
${PDPPILLOWURL}                                     https://puffy.com/products/puffy-pillow
${PDPBODYPILLOWURL}                                 https://puffy.com/products/puffy-body-pillow
${PDPMATTRESSPADURL}                                https://puffy.com/products/puffy-mattress-pad
${PDPPUFFYBLANKETURL}                               https://puffy.com/products/puffy-blanket
${PDPPUFFYSHEETSURL}                                https://puffy.com/products/puffy-sheets
${PDPPUFFYRUGURL}                                   https://puffy.com/products/puffy-area-rug
${PUFFY101NIGHTSLEEPTRIALURL}                       https://puffy.com/pages/puffy-mattress-sleep-trial
${PUFFYHOWITSMADEURL}                               https://puffy.com/pages/how-its-made
${PUFFYMATTRESSLAYERSURL}                           https://puffy.com/pages/puffy-sleep-system
${PUFFYPERFECTSLEEPURL}                             https://puffy.com/pages/puffy-perfect-sleep
${PUFFYCOMPAREMATTRESSURL}                          https://puffy.com/pages/puffy-mattress-and-puffy-lux
${PUFFYCOMPAREHYBRIDSURL}                           https://puffy.com/pages/compare-hybrid-mattress-puffy-lux-and-royal
${PUFFYDONATIONSURL}                                https://puffy.com/pages/puffy-donations-1
${PUFFYAFFILIATEPROGRAMURL}                         https://www.shareasale.com/shareasale.cfm?merchantID=73372
${PUFFYREFERAFRIENDURL}                             https://puffy.com/pages/share?traffic_source=site_footer
${PUFFYMATTRESSAWARDSURL}                           https://puffy.com/pages/top-rated-best-mattress-awards
${PUFFYGIFTSHOPURL}                                 https://puffy.com/pages/gift-shop
${PUFFYSTOREURL}                                    https://puffy.com/collections/puffy-store
${PUFFYBLOGURL}                                     https://puffy.com/blogs/in-the-clouds
${PUFFYREVIEWURL}                                   https://www.slumbersearch.com/puffy-mattress-reviews
${PUFFYLUXREVIEWURL}                                https://myslumberyard.com/mattress-reviews/puffy-lux-mattress-review/
${PUFFYROYALREVIEWURL}                              https://www.oursleepguide.com/mattress/puffy-royal-mattress-review/
${PUFFYMATTRESSREVIEWURL}                           https://www.mattressnerd.com/puffy-mattress-review/
${SUPPORTREVIEWSURL}                                https://puffy.com/pages/puffy-mattress-reviews
${SUPPORTCONTACTUSURL}                              https://puffy.com/pages/contact-puffy-mattress#contact_us
${SUPPORTFAQSURL}                                   https://puffy.com/pages/contact-puffy-mattress#faqs
${SUPPORTFINANCINGURL}                              https://puffy.com/pages/financing
${SUPPORTRETURNPOLICYURL}                           https://puffy.com/pages/return-policy
${SUPPORTPUFFYGUARANTEEURL}                         https://puffy.com/pages/puffy-mattress-sleep-guarantee
${AUXPRIVACYURL}                                    https://puffy.com/pages/puffy-privacy-policy
${AUXTERMSURL}                                      https://puffy.com/pages/terms-and-conditions
${AUXWARRANTYURL}                                   https://puffy.com/pages/puffy-mattress-warranty
${AUXDNSMPIURL}                                     https://puffy.com/pages/data-privacy
${SOCIALFACEBOOKURL}                                https://www.facebook.com/PuffyMattress/
${SOCIALTWITTERURL}                                 https://twitter.com/puffymattress
${SOCIALINSTAGRAMURL}                               https://www.instagram.com/puffymattress/
${SOCIALYOUTUBEURL}                                 https://www.youtube.com/channel/UCOJqN_xm1eR5lDMo3RIvN6A
${SOCIALLINKEDINURL}                                https://www.linkedin.com/company/puffy
${SOCIALPINTERESTURL}                               https://www.pinterest.com/puffymattressonline/
${AUXCOPYRIGHTURL}                                  https://puffy.com/
${PUFFYMILITARYURL}                                 https://puffy.com/pages/military-discount
${PUFFYHEALTHCAREURL}                               https://puffy.com/pages/healthcare-professional-discount
${SUPPORTREVIEWVIDEOSURL}                           https://puffy.com/pages/puffy-mattress-video-reviews
${HEADERPUFFYICONURL}                               https://puffy.com/
