*** Variables ***
${TEXTPUFFYMATTRESSH1}              Puffy Mattress
${TEXTPUFFYHYBRIDMATTRESSH1}        Puffy Hybrid Mattress
${TEXTPUFFYLUXMATTRESSH1}           Puffy Lux Mattress
${TEXTPUFFYLUXMATTRESSH2}           12 REASONS TO CHOOSE PUFFY LUX MATTRESS
${TEXTPUFFYLUXHYBRIDMATTRESSH1}     Puffy Lux Hybrid Mattress
${TEXTPUFFYLUXHYBRIDMATTRESSH2}     12 REASONS TO CHOOSE PUFFY LUX Hybrid MATTRESS
${TEXTPUFFYROYALMATTRESSH1}         Puffy Royal Mattress
${TEXTPUFFYROYALMATTRESSH2}         12 REASONS TO CHOOSE PUFFY ROYAL MATTRESS
${TEXTPUFFYROYALHYBRIDMATTRESSH1}   Puffy Royal Hybrid Mattress
${TEXTPUFFYROYALHYBRIDMATTRESSH2}   12 REASONS TO CHOOSE PUFFY ROYAL Hybrid MATTRESS
${TEXTPUFFYADJUSTABLEBASEH1}        Puffy Adjustable Base
${TEXTPUFFYFOUNDATIONH1}            Puffy Mattress Foundation
${TEXTPUFFYBEDFRAMEH1}              Puffy Bed Frame
${TEXTPUFFYCOMFORTERH1}             Puffy Comforter
${TEXTPUFFYPILLOWH1}                Puffy Pillow
${TEXTPUFFYBODYPILLOWH1}            Puffy Body Pillow
${TEXTPUFFYMATTRESSPADH1}           Puffy Mattress Pad
${TEXTPUFFYMATTRESSPROTECTORH1}     Puffy Mattress Protector
${TEXTPUFFYMATTRESSTOPPERH1}        Puffy Topper
${TEXTPUFFYBLANKETH1}               Puffy Blanket
${TEXTPUFFYWEIGHTEDBLANKETH1}       Puffy Weighted Blanket
${TEXTPUFFYSHEETSH1}                Puffy Sheets
${TEXTPUFFYDOGBEDH1}                Puffy Dog Bed
${TEXTPUFFYRUGH1}                   Puffy Rug
${TEXTPAYPALH1}                     Pay with PayPal
${TEXTSPLITITH1}                    How Splitit Works
${TEXTKLARNAH1}                     Option not available
${TEXTCARTDRAWERNOTE}               CHECKOUT
${TEXTCOMPAREPAGEH1}                CHOOSE YOUR PUFFY MATTRESS
${TEXTCARTDRAWERTITLE}              Your Puffy Cart
${TEXTPUFFYSTOREH1}                 PUFFY STORE
${TEXTPUFFYGIFTSHOPH1}              GIFT IDEAS FOR
${TEXTCHECKOUTINFORMATIONH1}        Contact information
${TEXTCHECKOUTSHIPPINGH1}           Shipping method
${TEXTCHECKOUTPAYMENTH1}            Payment
${TEXTPUFFYMATTRESSREVIEWSH1}       Puffy Mattress Reviews
${TEXTPUFFYMATTRESSREVIEWVIDEOSH1}  Puffy Mattress Review Videos
${TEXTPUFFYMATTRESSAWARDSH1}        Award-Winning
${TEXTCONTACTUSH1}                  Ask Away.
${TEXTFAQH2}                        Ask Away.
${TEXTFINANCINGH1}                  You choose how you pay
${TEXTSTOREH1}                      Puffy Store
${TEXTHOMEPAGEH1}                   Puffy Mattress
###########################################################FOOTER TESTCASES$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$##############
${FOOTERPUFFYMATTRESSSPELLING}                      Puffy
${FOOTERPUFFYLUXMATTRESSSPELLING}                   Puffy Lux
${FOOTERPUFFYROYALMATTRESSSPELLING}                 Puffy Royal
${FOOTERPUFFYHYBRIDMATTRESSSPELLING}                Puffy Hybrid
${FOOTERPUFFYCOMFORTERSPELLING}                     Comforter
${FOOTERPUFFYMATTRESSPROTECTORSPELLING}             Mattress Protector
${FOOTERPUFFYMATTRESSTOPPERSPELLING}                Mattress Topper
${FOOTERPUFFYWEIGHTEDBLANKETSPELLING}               Weighted Blanket
${FOOTERPUFFYDOGBEDSPELLING}                        Dog Bed
${FOOTERPUFFYBEDFRAMESPELLING}                      Bed Frame
${FOOTERPUFFYFOUNDATIONSPELLING}                    Foundation
${FOOTERPUFFYADJUSTABLEBASESPELLING}                Adjustable Base
${FOOTERPUFFYPILLOWSPELLING}                        Pillow
${FOOTERPUFFYBODYPILLOWSPELLING}                    Body Pillow
${FOOTERPUFFYMATTRESSPADSPELLING}                   Mattress Pad
${FOOTERPUFFYBLANKETSPELLING}                       Puffy Blanket
${FOOTERPUFFYSHEETSSPELLING}                        Puffy Sheets
${FOOTERPUFFYRUGSPELLING}                           Puffy Rug
${FOOTER101NIGHTSLEEPTRIALSPELLING}                 101-Night Sleep Trial
${FOOTERHOWITSMADESPELLING}                         How it’s Made
${FOOTERMATTRESSLAYERSSPELLING}                     Mattress Layers
${FOOTERPERFECTSLEEPSPELLING}                       Perfect Sleep
${FOOTERCOMPAREMATTRESSSPELLING}                    Compare Mattress
${FOOTERCOMPAREHYBRIDSSPELLING}                     Compare Hybrids
${FOOTERPUFFYDONATIONSSPELLING}                     Puffy Donations
${FOOTERAFFILIATEPROGRAMSPELLING}                   Affiliate Program
${FOOTERREFERAFRIENDSPELLING}                       Refer a Friend
${FOOTERMATTRESSAWARDSSPELLING}                     Mattress Awards
${FOOTERGIFTSHOPSPELLING}                           Gift Shop
${FOOTERPUFFYSTORESPELLING}                         Puffy Store
${FOOTERPUFFYBLOGSPELLING}                          Puffy Blog
${FOOTERPUFFYREVIEWSPELLING}                        Puffy Review
${FOOTERPUFFYLUXREVIEWSPELLING}                     Puffy Lux Review
${FOOTERPUFFYROYALREVIEWSPELLING}                   Puffy Royal Review
${FOOTERPUFFYMATTRESSREVIEWSPELLING}                Puffy Mattress Review
${FOOTERREVIEWSSPELLING}                            Reviews
${FOOTERCONTACTUSSPELLING}                          Contact Us
${FOOTERFAQSSPELLING}                               FAQs
${FOOTERFINANCINGSPELLING}                          Financing
${FOOTERRETURNPOLICYSPELLING}                       Return Policy
${FOOTERPUFFYGUARANTEESPELLING}                     Puffy Guarantee
${FOOTERPRIVACYSPELLING}                            Privacy
${FOOTERTERMSSPELLING}                              Terms
${FOOTERWARRANTYSPELLING}                           Warranty
${FOOTERCOPYRIGHTSPELLING}                          Puffy Mattress
${SIGNUPNODOMAIN}                                   email
${SIGNUPINVALIDEMAIL}                               email.com
${SIGNUPVALIDEMAIL}                                 email@gmail.com
####################################################MEGA MENU SPELLING CHECKS######################################################
${MENUPUFFYMATTRESSSPELLING}                        Puffy Mattress
${MENUPUFFYLUXMATTRESSSPELLING}                     Puffy Lux Mattress
${MENUPUFFYROYALMATTRESSSPELLING}                   Puffy Royal Mattress
${MENUPUFFYFOUNDATIONSPELLING}                      Foundation
${MENUPUFFYADJUSTABLEBASESPELLING}                  Adjustable Base
${MENUPUFFYBEDFRAMESPELLING}                        Bed Frame
${MENUPUFFYCOMFORTERSPELLING}                       Comforter
${MENUPUFFYPILLOWSPELLING}                          Pillow
${MENUPUFFYBODYPILLOWSPELLING}                      Body Pillow
${MENUPUFFYMATTRESSPADSPELLING}                     Mattress Pad
${MENUPUFFYMATTRESSPROTECTORSPELLING}               Mattress Protector
${MENUPUFFYMATTRESSTOPPERSPELLING}                  Mattress Topper
${MENUPUFFYBLANKETSPELLING}                         Blanket
${MENUPUFFYWEIGHTEDBLANKETSPELLING}                 Weighted Blanket
${MENUPUFFYSHEETSSPELLING}                          Sheets
${MENUPUFFYDOGBEDSPELLING}                          Dog Bed
${MENUPUFFYRUGSPELLING}                             Rug
${MENUCUSTOMERREVIEWSSPELLING}                      Customer Reviews
${MENUVIDEOREVIEWSSPELLING}                         Video Reviews
${MENUMENUAWARDSSPELLING}                           Awards
${MENUCONTACTUSSPELLING}                            Contact Us
${MENUFAQSSPELLING}                                 FAQs
${MENUFINANCINGSPELLING}                            Financing
${HEADERSTORESPELLING}                              STORE
###############################################################Checkout Texts#########################################################
${INFOTABHEADER}                                    Contact information
${ORDERSUMMARYDISCOUNTCODE1}                        DISCOUNT APPLIED (-$300.00)
${ORDERSUMMARYDISCOUNTCODE2}                        FREE KING PILLOW (-$95.00)
${ORDERSUMMARYDISCOUNTCODE3}                        FREE STANDARD PILLOW (-$75.00)
${ORDERSUMMARYDISCOUNTCODE4}                        FREE KING PILLOW (-$285.00)
${ORDERSUMMARYDISCOUNTCODE5}                        DISCOUNT APPLIED (-$350.00)
#PUFFY SHEETS
${ORDERSUMMARYPUFFYSHEETS}                          Puffy Sheets
${ORDERSUMMARYPUFFYSHEETSSIZECOLOR}                 White / Queen
${ORDERSUMMARYPUFFYSHEETSQTY}                       1
${ORDERSUMMARYPUFFYSHEETSPRICE}                     $125.00
#PUFFY BODY PILLOW
${ORDERSUMMARYPUFFYBODYPILLOW}                      Puffy Body Pillow
${ORDERSUMMARYPUFFYBODYPILLOWQTY}                   1
${ORDERSUMMARYPUFFYBODYPILLOWPRICE}                 $115.00
#PUFFY ADJUSTABLE BASE
${ORDERSUMMARYPUFFYADJUSTABLEBASE}                  Puffy Adjustable Base
${ORDERSUMMARYPUFFYADJUSTABLEBASESIZE}              Split King
${ORDERSUMMARYPUFFYADJUSTABLEBASEORIGINALPRICE}     $2,095.00
${ORDERSUMMARYPUFFYADJUSTABLEBASEDISCOUNTEDPRICE}   $1,795.00
${ORDERSUMMARYPUFFYADJUSTABLEBASEDISCOUNTEDPRICE350}   $1,745.00
${ORDERSUMMARYPUFFYADJUSTABLEBASEQTY}               1
#PUFFY ROYAL HYBRID MATTRESS
${ORDERSUMMARYPUFFYROYALHYBRIDMATTRESS}                  Puffy Royal Hybrid
${ORDERSUMMARYPUFFYROYALHYBRIDMATTRESSSIZE}              Twin XL
${ORDERSUMMARYPUFFYROYALHYBRIDMATTRESSORIGINALPRICE}     $1,745.00
${ORDERSUMMARYPUFFYROYALHYBRIDMATTRESSDISCOUNTEDPRICE}   $1,445.00
${ORDERSUMMARYPUFFYROYALHYBRIDMATTRESSDISCOUNTEDPRICE350}   $1,395.00
${ORDERSUMMARYPUFFYROYALHYBRIDMATTRESSQTY}               1
#PUFFY ROYAL MATTRESS
${ORDERSUMMARYPUFFYROYALMATTRESS}                  Puffy Royal
${ORDERSUMMARYPUFFYROYALMATTRESSSIZE}              Twin
${ORDERSUMMARYPUFFYROYALMATTRESSORIGINALPRICE}     $1,645.00
${ORDERSUMMARYPUFFYROYALMATTRESSDISCOUNTEDPRICE}   $1,345.00
${ORDERSUMMARYPUFFYROYALMATTRESSDISCOUNTEDPRICE350}   $1,295.00
${ORDERSUMMARYPUFFYROYALMATTRESSQTY}               1
#PUFFY LUX HYBRID MATTRESS
${ORDERSUMMARYPUFFYLUXHYBRIDMATTRESS}                  Puffy Lux Hybrid
${ORDERSUMMARYPUFFYLUXHYBRIDMATTRESSSIZE}              Cal King
${ORDERSUMMARYPUFFYLUXHYBRIDMATTRESSORIGINALPRICE}     $1,995.00
${ORDERSUMMARYPUFFYLUXHYBRIDMATTRESSDISCOUNTEDPRICE}   $1,695.00
${ORDERSUMMARYPUFFYLUXHYBRIDMATTRESSDISCOUNTEDPRICE350}   $1,645.00
${ORDERSUMMARYPUFFYLUXHYBRIDMATTRESSQTY}               1
#PUFFY LUX MATTRESS
${ORDERSUMMARYPUFFYLUXMATTRESS}                  Puffy Lux
${ORDERSUMMARYPUFFYLUXMATTRESSSIZE}              King
${ORDERSUMMARYPUFFYLUXMATTRESSORIGINALPRICE}     $1,995.00
${ORDERSUMMARYPUFFYLUXMATTRESSDISCOUNTEDPRICE}   $1,695.00
${ORDERSUMMARYPUFFYLUXMATTRESSDISCOUNTEDPRICE350}   $1,645.00
${ORDERSUMMARYPUFFYLUXMATTRESSQTY}               1
#PUFFY MATTRESS
${ORDERSUMMARYPUFFYMATTRESS}                  Puffy Mattress
${ORDERSUMMARYPUFFYMATTRESSSIZE}              Queen
${ORDERSUMMARYPUFFYMATTRESSORIGINALPRICE}     $1,150.00
${ORDERSUMMARYPUFFYMATTRESSDISCOUNTEDPRICE}   $850.00
${ORDERSUMMARYPUFFYMATTRESSDISCOUNTEDPRICE350}   $800.00
${ORDERSUMMARYPUFFYMATTRESSQTY}               1
#FREE PUFFY PILLOW STANDARD
${ORDERSUMMARYPUFFYPILLOWSTANDARD}                  Free Puffy Pillow
${ORDERSUMMARYPUFFYPILLOWSTANDARDSIZE}              Standard
${ORDERSUMMARYPUFFYPILLOWSTANDARDORIGINALPRICE}     $75.00
${ORDERSUMMARYPUFFYPILLOWSTANDARDDISCOUNTEDPRICE}   Free
${ORDERSUMMARYPUFFYPILLOWSTANDARDQTY}               1
#FREE PUFFY PILLOW KING WHITE
${ORDERSUMMARYPUFFYPILLOWKINGWHITE}                  Free Puffy Pillow
${ORDERSUMMARYPUFFYPILLOWKINGWHITESIZE}              King
${ORDERSUMMARYPUFFYPILLOWKINGWHITEORIGINALPRICE}     $95.00
${ORDERSUMMARYPUFFYPILLOWKINGWHITEDISCOUNTEDPRICE}   Free
${ORDERSUMMARYPUFFYPILLOWKINGWHITEQTY}               1
#FREE PUFFY PILLOW KING GRAY
${ORDERSUMMARYPUFFYPILLOWKINGGRAY}                  Free Puffy Pillow
${ORDERSUMMARYPUFFYPILLOWKINGGRAYSIZE}              King
${ORDERSUMMARYPUFFYPILLOWKINGGRAYORIGINALPRICE}     $285.00
${ORDERSUMMARYPUFFYPILLOWKINGGRAYDISCOUNTEDPRICE}   Free
${ORDERSUMMARYPUFFYPILLOWKINGGRAYQTY}               3
#TOTAL SAVINGS AMOUNT
${TOTALSAVINGS}                                     $2,255
${TOTALSAVINGS350}                                     $2,555
#SUBTOTAL
${SUBTOTAL}                                         $9,065.00
${SUBTOTAL350}                                         $8,765.00
#SHIPPING
${SHIPPING}                                         Free
${TOTAL}                                            $9,065.00
${TOTAL350}                                            $8,765.00


