*** Settings ***
Documentation    Suite description
Library             Selenium2Library
#Library             SeleniumLibrary
Library             ScreenCapLibrary
Library             Collections
Library             String


*** Variables ***
${LOCMATTRESSES}                    css=body > div.shopify-section.header-section > div > header.main_header > div > div > div > div.nav > ul > li:nth-child(1) > a
${LOCPUFFYMATTRESS}                 css=body > div.shopify-section.header-section > div > header.main_header > div > div > div > div.dropdown_container.mega-menu.mega-menu-1 > div > div.dropdown_content > div:nth-child(1) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCPUFFYLUXMATTRESS}              css=body > div.shopify-section.header-section > div > header.main_header > div > div > div > div.dropdown_container.mega-menu.mega-menu-1 > div > div.dropdown_content > div:nth-child(2) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCPUFFYROYALMATTRESS}            css=body > div.shopify-section.header-section > div > header.main_header > div > div > div > div.dropdown_container.mega-menu.mega-menu-1 > div > div.dropdown_content > div:nth-child(3) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCCOMPARE}                       css=body > div.shopify-section.header-section > div > header.main_header > div > div > div > div.dropdown_container.mega-menu.mega-menu-1 > div > div.dropdown-compare > a
${LOCPUFFYREASON1IMAGE}             //*[@id="productReasons"]/div[2]/div[1]/div/div/div/div/div[2]/div/img
${LOCBASES}                         css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.nav > ul > li:nth-child(2) > a
${LOCFOUNDATION}                    css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-2 > div > div > div:nth-child(1) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCADJUSTABLEBASE}                css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-2 > div > div > div:nth-child(2) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCBEDFRAME}                      css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-2 > div > div > div:nth-child(3) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCBEDDING}                       css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.nav > ul > li:nth-child(3) > a
${LOCCOMFORTER}                     css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(1) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCPILLOW}                        css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(2) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCBODYPILLOW}                    css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(3) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCMATTRESSPAD}                   css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(4) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCMATTRESSPROTECTOR}             css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(5) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCTOPPER}                        css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(6) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCBLANKET}                       css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(7) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCWEIGHTEDBLANKET}               css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(8) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCSHEETS}                        css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(9) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCBEDROOM}                       css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.nav > ul > li:nth-child(4) > a
${LOCREVIEWS}                       css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.nav > ul > li:nth-child(5) > a
${LOCFEEDBACK}                      html.null body.index.is--hybrid-false.timer--exists.jdgm-buyer-badge--removed div.index-sections div#shopify-section-hov_instagramBoxes.shopify-section div.instagram-boxes div.instagram-boxes__inner
${LOCSTORE}                         css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(3) > div > div > ul > li:nth-child(12) > p > a
${LOCLOGO}                          css=body > div.shopify-section.header-section > div > header.main_header > div > div > div > div.logo
${LOCCARTHEADER}                    css=body > div.cart_content.jsCartContent.cart-content-mob > div.cart-close > span.cart-close__title
${LOCCONTACTS}                      //*[@id="contact"]/a
${LOCDOGBED}                        css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-4 > div > div > div:nth-child(1) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCRUG}                           css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-4 > div > div > div:nth-child(2) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCCART}                          css=body > div.shopify-section.header-section > div > header.main_header > div > div > div > div.cart_container > div > a
${LOCBLACKFRIDAYSALEMENUBUTTON}     css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.nav > ul > li.menu__item.menu__item--sale > a
${LOC12REASONSPDP}                  css=#productReasons > div.block__rich_text_and_image.block__product-pad-template-0 > div > div > div > h2
${LOCTOGGLEA}                       css=#showVersionA
${LOCTOGGLEB}                       css=#showVersionB
${LOCTOGGLEC}                       css=#showVersionC
###########################################################FOOTER TESTCASES$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$##############
${LOCSIGNUPTEXTFIELD}               css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(4) > div > div.newsletter-wrapper > div > div > div > div > form > div > div > div.needsclick.FormComponent__StyledFormComponentWrapper-e0xun6-0.kyRZKh.notranslate.kl-private-reset-css-Xuajs1 > div > input
${LOCFOOTERSIGNUP}                  css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(4) > div > div.newsletter-wrapper > div > div > div > div > form > div > div > div.needsclick.FormComponent__StyledFormComponentWrapper-e0xun6-0.kUeWNY.notranslate.kl-private-reset-css-Xuajs1 > button
${LOCFOOTERPUFFY}                   css=.footer-menu__link[href="/products/puffy-mattress"]
${LOCFOOTERPUFFYLUX}                css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(1) > div > div > ul > li:nth-child(2) > a
${LOCFOOTERPUFFYROYAL}              css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(1) > div > div > ul > li:nth-child(3) > a
${LOCFOOTERPUFFYHYBRID}             css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(1) > div > div > ul > li:nth-child(4) > a
${LOCFOOTERCOMFORTER}               css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(1) > div > div > ul > li:nth-child(5) > a
${LOCFOOTERMATTRESSPROTECTOR}       css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(1) > div > div > ul > li:nth-child(6) > a
${LOCFOOTERMATTRESSTOPPER}          css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(1) > div > div > ul > li:nth-child(7) > a
${LOCFOOTERWEIGHTEDBLANKET}         css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(1) > div > div > ul > li:nth-child(8) > a
${LOCFOOTERDOGBED}                  css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(1) > div > div > ul > li:nth-child(9) > a
${LOCFOOTERBEDFRAME}                css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(1) > div > div > ul > li:nth-child(10) > a
${LOCFOOTERFOUNDATION}              css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(1) > div > div > ul > li:nth-child(11) > a
${LOCFOOTERADJUSTABLEBASE}          css=.footer-menu__link[href="/products/puffy-adjustable-base"]
${LOCFOOTERPILLOW}                  css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(1) > div > div > ul > li:nth-child(13) > a
${LOCFOOTERBODYPILLOW}              css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(1) > div > div > ul > li:nth-child(14) > a
${LOCFOOTERMATTRESSPAD}             css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(1) > div > div > ul > li:nth-child(15) > a
${LOCFOOTERPUFFYBLANKET}            css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(1) > div > div > ul > li:nth-child(16) > a
${LOCFOOTERPUFFYSHEETS}             css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(1) > div > div > ul > li:nth-child(17) > a
${LOCFOOTERPUFFYRUG}                css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(1) > div > div > ul > li:nth-child(18) > a
${LOCFOOTERSECTION}                 css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(2) > div
${LOCFOOTER101NIGHTSLEEPTRIAL}      css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(2) > div > div > ul > li:nth-child(1) > a
${LOCFOOTERHOWITSMADE}              css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(2) > div > div > ul > li:nth-child(2) > a
${LOCFOOTERMATTRESSLAYERS}          css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(2) > div > div > ul > li:nth-child(3) > a
${LOCFOOTERPERFECTSLEEP}            css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(2) > div > div > ul > li:nth-child(4) > a
${LOCFOOTERMATTRESSAWARDS}          css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(2) > div > div > ul > li:nth-child(5) > a
${LOCFOOTERCOMPAREMATTRESS}         css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(2) > div > div > ul > li:nth-child(6) > a
${LOCFOOTERCOMPAREHYBRIDS}          css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(2) > div > div > ul > li:nth-child(7) > a
${LOCFOOTERPUFFYDONATIONS}          css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(2) > div > div > ul > li:nth-child(8) > a
${LOCFOOTERAFFILIATEPROGRAM}        css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(2) > div > div > ul > li:nth-child(9) > a
${LOCFOOTERREFERAFRIEND}            css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(2) > div > div > ul > li:nth-child(10) > a
${LOCFOOTERGIFTSHOP}                css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(2) > div > div > ul > li:nth-child(11) > a
${LOCFOOTERPUFFYSTORE}              css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(2) > div > div > ul > li:nth-child(12) > a
${LOCFOOTERPUFFYBLOG}               css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(2) > div > div > ul > li:nth-child(13) > a
${LOCFOOTERPUFFYREVIEW}             css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(2) > div > div > ul > li:nth-child(14) > a
${LOCFOOTERPUFFYLUXREVIEW}          css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(2) > div > div > ul > li:nth-child(15) > a
${LOCFOOTERPUFFYROYALREVIEW}        css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(2) > div > div > ul > li:nth-child(16) > a
${LOCFOOTERPUFFYMATTRESSREVIEW}     css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(2) > div > div > ul > li:nth-child(17) > a
${LOCFOOTERHEALTHCAREDISCOUNT}      css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(2) > div > div > ul > li:nth-child(18) > a
${LOCFOOTERMILITARYDISCOUNT}        css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(2) > div > div > ul > li:nth-child(19) > a
${LOCFOOTERREVIEWS}                 css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(3) > div > div > ul > li:nth-child(1) > a
${LOCFOOTERCONTACTUS}               css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(3) > div > div > ul > li:nth-child(2) > a
${LOCFOOTERFAQS}                    css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(3) > div > div > ul > li:nth-child(3) > a
${LOCFOOTERFINANCING}               css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(3) > div > div > ul > li:nth-child(4) > a
${LOCFOOTERRETURNPOLICY}            css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(3) > div > div > ul > li:nth-child(5) > a
${LOCFOOTERPUFFYGUARANTEE}          css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(3) > div > div > ul > li:nth-child(6) > a
${LOCFOOTERPRIVACY}                 css=#shopify-section-footer > footer > div.footer-bottom > div > div:nth-child(1) > div > a:nth-child(1)
${LOCFOOTERTERMS}                   css=#shopify-section-footer > footer > div.footer-bottom > div > div:nth-child(1) > div > a:nth-child(2)
${LOCFOOTERWARRANTY}                css=#shopify-section-footer > footer > div.footer-bottom > div > div:nth-child(1) > div > a:nth-child(3)
${LOCFOOTERDNSMPI}                  css=#shopify-section-footer > footer > div.footer-bottom > div > div.columns.column-custom-width > div > a.menu-bottom-desktop
${LOCFOOTERFACEBOOK}                css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(4) > div > ul > li:nth-child(1) > a
${LOCFOOTERTWITTER}                 css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(4) > div > ul > li:nth-child(2) > a
${LOCFOOTERINSTAGRAM}               css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(4) > div > ul > li:nth-child(3) > a
${LOCFOOTERYOUTUBE}                 css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(4) > div > ul > li:nth-child(4) > a
${LOCFOOTERLINKEDIN}                css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(4) > div > ul > li:nth-child(5) > a
${LOCFOOTERPINTEREST}               css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(4) > div > ul > li:nth-child(6) > a
${LOCFOOTERCOPYRIGHT}               css=#shopify-section-footer > footer > div.footer-bottom > div > div:nth-child(2) > div > p > a
${LOCFOOTERHEALTHCARE}              css=#shopify-section-footer > footer > div.container.footer-menu-wrap > div:nth-child(2) > div > div > ul > li:nth-child(18) > a
${LOCMENUREVIEWS}                   css=body > div.shopify-section.header-section > div > header.main_header > div > div > div > div.nav > ul > li:nth-child(5) > a
#################################################################MEGA MENU LOCATORS#################################################################
${LOCMENUPUFFYLUXMATTRESSTEXT}                      css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-1 > div > div.dropdown_content > div:nth-child(2) > div.mega-menu__image-caption-link > a > div.menunew > p
${LOCMENUPUFFYMATTRESSTEXT}                         css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-1 > div > div.dropdown_content > div:nth-child(1) > div.mega-menu__image-caption-link > a > div.menunew > p
${LOCMENUPUFFYROYALMATTRESSTEXT}                    css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-1 > div > div.dropdown_content > div:nth-child(3) > div.mega-menu__image-caption-link > a > div.menunew > p
${LOCMENUPUFFYFOUNDATIONTEXT}                       css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-2 > div > div > div:nth-child(1) > div.mega-menu__image-caption-link > a > div.menunew > p
${LOCMENUPUFFYADJUSTABLEBASETEXT}                   css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-2 > div > div > div:nth-child(2) > div.mega-menu__image-caption-link > a > div.menunew > p
${LOCMENUPUFFYBEDFRAMETEXT}                         css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-2 > div > div > div:nth-child(3) > div.mega-menu__image-caption-link > a > div.menunew > p
${LOCMENUPUFFYCOMFORTERTEXT}                        css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(1) > div.mega-menu__image-caption-link > a > div.menunew > p
${LOCMENUPUFFYPILLOWTEXT}                           css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(2) > div.mega-menu__image-caption-link > a > div.menunew > p
${LOCMENUPUFFYBODYPILLOWTEXT}                       css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(3) > div.mega-menu__image-caption-link > a > div.menunew > p
${LOCMENUPUFFYMATTRESSPADTEXT}                      css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(4) > div.mega-menu__image-caption-link > a > div.menunew > p
${LOCMENUPUFFYMATTRESSPROTECTORTEXT}                css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(5) > div.mega-menu__image-caption-link > a > div.menunew > p
${LOCMENUPUFFYMATTRESSTOPPERTEXT}                   css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(6) > div.mega-menu__image-caption-link > a > div.menunew > p
${LOCMENUPUFFYBLANKETTEXT}                          css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(7) > div.mega-menu__image-caption-link > a > div.menunew > p
${LOCMENUPUFFYWEIGHTEDBLANKETTEXT}                  css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(8) > div.mega-menu__image-caption-link > a > div.menunew > p
${LOCMENUPUFFYSHEETSTEXT}                           css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(9) > div.mega-menu__image-caption-link > a > div.menunew > p
${LOCMENUPUFFYDOGBEDTEXT}                           css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-4 > div > div > div:nth-child(1) > div.mega-menu__image-caption-link > a > div.menunew > p
${LOCMENUPUFFYRUGTEXT}                              css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-4 > div > div > div:nth-child(2) > div.mega-menu__image-caption-link > a > div.menunew > p
${LOCMENUPUFFYMATTRESSIMAGE}                        css=body > div.shopify-section.header-section > div > header.main_header > div > div > div > div.dropdown_container.mega-menu.mega-menu-1 > div > div.dropdown_content > div:nth-child(1) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCMENUPUFFYLUXMATTRESSIMAGE}                     css=body > div.shopify-section.header-section > div > header.main_header > div > div > div > div.dropdown_container.mega-menu.mega-menu-1 > div > div.dropdown_content > div:nth-child(2) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCMENUPUFFYROYALMATTRESSIMAGE}                   css=body > div.shopify-section.header-section > div > header.main_header > div > div > div > div.dropdown_container.mega-menu.mega-menu-1 > div > div.dropdown_content > div:nth-child(3) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCMENUPUFFYFOUNDATIONIMAGE}                      css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-2 > div > div > div:nth-child(1) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCMENUPUFFYADJUSTABLEBASEIMAGE}                  css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-2 > div > div > div:nth-child(2) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCMENUPUFFYBEDFRAMEIMAGE}                        css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-2 > div > div > div:nth-child(3) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCMENUPUFFYCOMFORTERIMAGE}                       css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(1) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCMENUPUFFYPILLOWIMAGE}                          css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(2) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCMENUPUFFYBODYPILLOWIMAGE}                      css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(3) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCMENUPUFFYMATTRESSPADIMAGE}                     css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(4) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCMENUPUFFYMATTRESSPROTECTORIMAGE}               css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(5) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCMENUPUFFYMATTRESSTOPPERIMAGE}                  css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(6) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCMENUPUFFYBLANKETIMAGE}                         css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(7) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCMENUPUFFYWEIGHTEDBLANKETIMAGE}                 css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(8) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCMENUPUFFYSHEETSIMAGE}                          css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-3.boxes--9 > div > div > div:nth-child(9) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCMENUPUFFYDOGBEDIMAGE}                          css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-4 > div > div > div:nth-child(1) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCMENUPUFFYRUGIMAGE}                             css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.dropdown_container.mega-menu.mega-menu-4 > div > div > div:nth-child(2) > div.mega-menu__image-caption-link > a > div.image-element__wrap > img
${LOCMENUCUSTOMERREVIEWS}                           css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.nav > ul > li:nth-child(5) > div > div > div > ul > li:nth-child(1) > a
${LOCMENUVIDEOREVIEWS}                              css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.nav > ul > li:nth-child(5) > div > div > div > ul > li:nth-child(2) > a
${LOCMENUAWARDS}                                    css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.nav > ul > li:nth-child(5) > div > div > div > ul > li:nth-child(3) > a
${LOCMENUCONTACTUS}                                 css=body > div.shopify-section.header-section > div > header.main_header > div > div > div > div.nav > ul > li:nth-child(6) > div > div > div > ul > li:nth-child(1) > a
${LOCMENUCHAT}                                      css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.nav > ul > li:nth-child(6) > div > div > div > ul > li:nth-child(1) > a
${LOCMENUCONTACTUS}                                      css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.nav > ul > li:nth-child(6) > div > div > div > ul > li:nth-child(2) > a
${LOCMENUFAQS}                                      css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.nav > ul > li:nth-child(6) > div > div > div > ul > li:nth-child(3) > a
${LOCMENUFINANCING}                                 css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.nav > ul > li:nth-child(6) > div > div > div > ul > li:nth-child(4) > a
${LOCHEADERSTORE}                                            css=.store-button--desktop
${LOCHEADERPUFFYLOGO}                                  css=body > div.shopify-section.header-section > div > header.main_header > div > div > div > div.logo
${LOCSUPPORT}                       css=body > div.shopify-section.header-section > div > header.main_header > div > div > div > div.nav > ul > li:nth-child(6) > a
#${LOCSUPPORT}                       css=body > div.shopify-section.header-section > div > header.main_header.feature_image > div > div > div > div.nav > ul > li:nth-child(6) > a
${LOCFOOTERBREADCRUMB}              css=#shopify-section-footer > footer > div.footer-breadcrumbs-wrap.container > div > nav
###################################CONTACT US LOCATORS###########################
${LOCCONTACTUSTITLE}                   css=#contact_us > div > div > aside.left-side > h2
${LOCCONTACTUSTITLEDESCRIPTION}        css=#contact_us > div > div > aside.left-side > div
${LOCCONTACTUSEMAILICON}               css=#contact_us > div > div > aside.right-side > div:nth-child(1) > a > img
${LOCSENDUSANEMAIL}                    css=#contact_us > div > div > aside.right-side > div:nth-child(1) > a > strong.contact-details__details
${LOCCONTACTUSEMAILADD}                css=#contact_us > div > div > aside.right-side > div:nth-child(1) > a > strong:nth-child(4)
${LOCCONTACTUSPHONEICON}               css=#contact_us > div > div > aside.right-side > div:nth-child(3) > a > img
${LOCGIVEUSACALL}                      css=#contact_us > div > div > aside.right-side > div:nth-child(3) > a > strong.contact-details__details
${LOCCONTACTUSPHONENUMBER}             css=#contact_us > div > div > aside.right-side > div:nth-child(3) > a > strong:nth-child(4)
${LOCCONTACTUSFORMSUBJECT}             css=#contact_form > div:nth-child(3)
${LOCCONTACTUSNAMELABEL}               css=#contact_form > div:nth-child(5) > div:nth-child(1) > label
${LOCCONTACTUSEMAILLABEL}              css=#contact_form > div:nth-child(5) > div:nth-child(2) > label
${LOCCONTACTUSREASONLABEL}             css=#contact_form > div:nth-child(6) > div > label
${LOCCONTACTUSMESSAGELABEL}            css=#contact_form > div:nth-child(8) > div > label
${LOCCONTACTUSSENDMESSAGE}             css=#contact_form > div:nth-child(9) > div > input
${LOCCONTACTUSNAMETEXTBOX}             css=#contactFormName
${LOCCONTACTUSEMAILTEXTBOX}            css=#contactFormEmail
${LOCCONTACTUSREASONDROPDOWNBOX}       css=#contact-category
${LOCCONTACTUSMESSAGETEXTBOX}          css=#contactFormMessage
${LOCCONTACTUSORDERNUMBERTEXTBOX}      css=#contactFormOrderNumber
${LOCFINANCINGTOPBANNERIMAGE}          css=body > div.top-banner.mobile--left-aligned > div.top-banner__image > div:nth-child(1) > img
${LOCFINANCINGTOPBANNERTITLE}          css=body > div.top-banner.mobile--left-aligned > div.top-banner__inner > div > h1
${LOCFINANCINGTOPBANNERTITLEDESC}      css=body > div.top-banner.mobile--left-aligned > div.top-banner__inner > div > h2
${LOCFINANCINGTOPBANNERCTA}            css=body > div.top-banner.mobile--left-aligned > div.top-banner__inner > div > div > a
${LOCFINANCINGKLARNAHEADER}            css=body > div.financing__klarna > div.featured-financing.text-bar > h3
${LOCFINANCINGFINANCEOPTIONHEADER}     css=body > div.text-bar.text-bar--financing > div.text-bar__inner > h2
${LOCFINANCINGFINANCEKLARNAIMAGE}      css=body > div.text-bar.text-bar--financing > div.text-bar__inner > div > div.text-bar__klarna > div
${LOCFINANCINGFINANCESPLITITIMAGE}     css=body > div.text-bar.text-bar--financing > div.text-bar__inner > div > div.text-bar__splitit > div
${LOCFINANCINGKLARNASUMMARY}           css=body > div.text-bar.text-bar--financing > div.text-bar__inner > div > div.text-bar__klarna > ul
${LOCFINANCINGKLARNASUMMARYFIRST}      css=body > div.text-bar.text-bar--financing > div.text-bar__inner > div > div.text-bar__klarna > ul > li:nth-child(1)
${LOCFINANCINGKLARNASUMMARYSECOND}     css=body > div.text-bar.text-bar--financing > div.text-bar__inner > div > div.text-bar__klarna > ul > li:nth-child(2)
${LOCFINANCINGKLARNASUMMARYTHIRD}      css=body > div.text-bar.text-bar--financing > div.text-bar__inner > div > div.text-bar__klarna > ul > li:nth-child(3)
${LOCFINANCINGKLARNASUMMARYFOURTH}     css=body > div.text-bar.text-bar--financing > div.text-bar__inner > div > div.text-bar__klarna > ul > li:nth-child(4)
${LOCFINANCINGKLARNASEEDETAILS}        css=body > div.text-bar.text-bar--financing > div.text-bar__inner > div > div.text-bar__klarna > a
${LOCFINANCINGSPLITITSUMMARY}          css=body > div.text-bar.text-bar--financing > div.text-bar__inner > div > div.text-bar__splitit > ul
${LOCFINANCINGSPLITITSUMMARYFIRST}     css=body > div.text-bar.text-bar--financing > div.text-bar__inner > div > div.text-bar__splitit > ul > li:nth-child(1)
${LOCFINANCINGSPLITITSUMMARYSECOND}    css=body > div.text-bar.text-bar--financing > div.text-bar__inner > div > div.text-bar__splitit > ul > li:nth-child(2)
${LOCFINANCINGSPLITITSUMMARYTHIRD}     css=body > div.text-bar.text-bar--financing > div.text-bar__inner > div > div.text-bar__splitit > ul > li:nth-child(3)
${LOCFINANCINGSPLITITSUMMARYFOURTH}    css=body > div.text-bar.text-bar--financing > div.text-bar__inner > div > div.text-bar__splitit > ul > li:nth-child(4)
${LOCFINANCINGSPLITITSEEDETAILS}       css=body > div.text-bar.text-bar--financing > div.text-bar__inner > div > div.text-bar__splitit > a
${LOCKLARNAFINANCETITLE}               css=body > div.financing__klarna > div.featured-financing.text-bar > h3
${LOCKLARNAFINANCETITLEDESC}           css=body > div.financing__klarna > div.featured-financing.text-bar > div.featured-financing__desc
${LOCKLARNAAPRFINANCINGICON}           css=body > div.financing__klarna > div.featured-financing.text-bar > div.feature-icons > div > div > div:nth-child(1) > div.feature-icons__icon > svg
${LOCKLARNAAPRFINANCINGTITLE}          css=body > div.financing__klarna > div.featured-financing.text-bar > div.feature-icons > div > div > div:nth-child(1) > h2
${LOCKLARNAAPRFINANCINGTITLEDESC}      css=body > div.financing__klarna > div.featured-financing.text-bar > div.feature-icons > div > div > div:nth-child(1) > div.feature-icons__desc
${LOCKLARNAAPPLYINMINICON}             css=body > div.financing__klarna > div.featured-financing.text-bar > div.feature-icons > div > div > div:nth-child(2) > div.feature-icons__icon > svg
${LOCKLARNAAPPLYINMINTITLE}            css=body > div.financing__klarna > div.featured-financing.text-bar > div.feature-icons > div > div > div:nth-child(2) > h2
${LOCKLARNAAPPLYINMINTITLEDESC}        css=body > div.financing__klarna > div.featured-financing.text-bar > div.feature-icons > div > div > div:nth-child(2) > div.feature-icons__desc
${LOCKLARNASIMPLEREPAYMENTSICON}       css=body > div.financing__klarna > div.featured-financing.text-bar > div.feature-icons > div > div > div:nth-child(3) > div.feature-icons__icon > svg
${LOCKLARNASIMPLEREPAYMENTSTITLE}      css=body > div.financing__klarna > div.featured-financing.text-bar > div.feature-icons > div > div > div:nth-child(3) > h2
${LOCKLARNASIMPLEREPAYMENTSTITLEDESC}  css=body > div.financing__klarna > div.featured-financing.text-bar > div.feature-icons > div > div > div:nth-child(3) > div.feature-icons__desc
${LOCSELECTKLARNA}                     css=body > div.financing__klarna > div.featured-financing.text-bar > h2
${LOCKLARNAFIRSTFAQ}                   css=body > div.financing__klarna > div.featured-financing__faq.featured-financing__faq--klarna.text-bar > div > div > div > div > ul > li:nth-child(1) > h4
${LOCKLARNAFIRSTFAQANSWER}             css=body > div.financing__klarna > div.featured-financing__faq.featured-financing__faq--klarna.text-bar > div > div > div > div > ul > li:nth-child(1) > section
${LOCKLARNASECONDFAQ}                  css=body > div.financing__klarna > div.featured-financing__faq.featured-financing__faq--klarna.text-bar > div > div > div > div > ul > li:nth-child(2) > h4
${LOCKLARNASECONDFAQANSWER}            css=body > div.financing__klarna > div.featured-financing__faq.featured-financing__faq--klarna.text-bar > div > div > div > div > ul > li:nth-child(2) > section
${LOCKLARNATHIRDFAQ}                   css=body > div.financing__klarna > div.featured-financing__faq.featured-financing__faq--klarna.text-bar > div > div > div > div > ul > li:nth-child(3) > h4
${LOCKLARNATHIRDFAQANSWER}             css=body > div.financing__klarna > div.featured-financing__faq.featured-financing__faq--klarna.text-bar > div > div > div > div > ul > li:nth-child(3) > section
${LOCKLARNADISCLAIMER}                 css=body > div.financing__klarna > div.text-bar.text-bar--small-text.text-bar--financing-info > div.text-bar__inner > div > p
${LOCKLARNACTA}                        css=body > div.financing__klarna > div.featured-financing__faq.featured-financing__faq--klarna.text-bar > div > a
${LOCSPLITITFINANCETITLE}              css=body > div.financing__splitit > div.featured-financing.text-bar > h3
${LOCSPLITITFINANCETITLEDESC}          css=body > div.financing__splitit > div.featured-financing.text-bar > div.featured-financing__desc
${LOCSPLITITSPLITYOURPAYMENTICON}      css=body > div.financing__splitit > div.featured-financing.text-bar > div.feature-icons.feature-icons--splitit > div > div > div:nth-child(1) > div.feature-icons__icon
${LOCSPLITITSPLITYOURPAYMENTTITLE}     css=body > div.financing__splitit > div.featured-financing.text-bar > div.feature-icons.feature-icons--splitit > div > div > div:nth-child(1) > h2
${LOCSPLITITSPLITYOURPAYMENTTITLEDESC}  css=body > div.financing__splitit > div.featured-financing.text-bar > div.feature-icons.feature-icons--splitit > div > div > div:nth-child(1) > div.feature-icons__desc
${LOCSPLITITNOAPPLICATIONICON}         css=body > div.financing__splitit > div.featured-financing.text-bar > div.feature-icons.feature-icons--splitit > div > div > div:nth-child(2) > div.feature-icons__icon
${LOCSPLITITNOAPPLICATIONTITLE}        css=body > div.financing__splitit > div.featured-financing.text-bar > div.feature-icons.feature-icons--splitit > div > div > div:nth-child(2) > h2
${LOCSPLITITNOAPPLICATIONTITLEDESC}    css=body > div.financing__splitit > div.featured-financing.text-bar > div.feature-icons.feature-icons--splitit > div > div > div:nth-child(2) > div.feature-icons__desc
${LOCSPLITITTAKEADVANTAGEICON}         css=body > div.financing__splitit > div.featured-financing.text-bar > div.feature-icons.feature-icons--splitit > div > div > div:nth-child(3) > div.feature-icons__icon
${LOCSPLITITTAKEADVANTAGETITLE}        css=body > div.financing__splitit > div.featured-financing.text-bar > div.feature-icons.feature-icons--splitit > div > div > div:nth-child(3) > h2
${LOCSPLITITTAKEADVANTAGETITLEDESC}    css=body > div.financing__splitit > div.featured-financing.text-bar > div.feature-icons.feature-icons--splitit > div > div > div:nth-child(3) > div.feature-icons__desc
${LOCSELECTSPITIT}                     css=body > div.financing__splitit > div.featured-financing.text-bar > h2
${LOCSPLITITFIRSTFAQ}                  css=body > div.financing__splitit > div.featured-financing__faq.featured-financing__faq--splitit.text-bar > div > div > div > div > ul > li:nth-child(1) > h4
${LOCSPLITITSECONDFAQ}                 css=body > div.financing__splitit > div.featured-financing__faq.featured-financing__faq--splitit.text-bar > div > div > div > div > ul > li:nth-child(2) > h4
${LOCSPLITITTHIRDFAQ}                  css=body > div.financing__splitit > div.featured-financing__faq.featured-financing__faq--splitit.text-bar > div > div > div > div > ul > li:nth-child(3) > h4
${LOCSPLITITFIRSTFAQANSWER}            css=body > div.financing__splitit > div.featured-financing__faq.featured-financing__faq--splitit.text-bar > div > div > div > div > ul > li:nth-child(1) > section
${LOCSPLITITSECONDFAQANSWER}           css=body > div.financing__splitit > div.featured-financing__faq.featured-financing__faq--splitit.text-bar > div > div > div > div > ul > li:nth-child(2) > section
${LOCSPLITITTHIRDFAQANSWER}            css=body > div.financing__splitit > div.featured-financing__faq.featured-financing__faq--splitit.text-bar > div > div > div > div > ul > li:nth-child(3) > section
${LOCSPLITITDISCLAIMER}                css=body > div.financing__splitit > div.text-bar.text-bar--small-text.text-bar--financing-info > div > div > p
${LOCSPLITITCTA}                       css=body > div.financing__splitit > div.featured-financing__faq.featured-financing__faq--splitit.text-bar > div > a
######################################RETURN POLICY#####################################
${LOCRETURNPOLICYTITLE}                css=body > div.container.content > div > h1
${LOCRETURNPOLICYINFORMATION}          css=body > div.container.content > div > div:nth-child(3) > p:nth-child(1)
${LOCWHYBUYPUFFYTITLE}                 css=body > div.container.content > div > div:nth-child(3) > h2:nth-child(2)
${LOCWHYBUYPUFFYINFORMATION}           css=body > div.container.content > div > div:nth-child(3) > p:nth-child(3)
${LOCWHYBUYPUFFYHYPERLINKPUFFY}        css=body > div.container.content > div > div:nth-child(3) > p:nth-child(3) > a
${LOCPUFFYMATTRESSRETURNSTITLE}        css=body > div.container.content > div > div:nth-child(3) > h2:nth-child(4)
${LOCPUFFYMATTRESSRETURNSINFORMATION1}  css=body > div.container.content > div > div:nth-child(3) > p:nth-child(5)
${LOCPUFFYMATTRESSRETURNSINFORMATION2}  css=body > div.container.content > div > div:nth-child(3) > p:nth-child(6)
${LOCPUFFYMATTRESSRETURNSINFORMATION3}  css=body > div.container.content > div > div:nth-child(3) > p:nth-child(7)
${LOCPUFFYMATTRESSHYPERLINK}            css=body > div.container.content > div > div:nth-child(3) > p:nth-child(5) > a
${LOCPUFFYPRODUCTRETURNSTITLE}          css=body > div.container.content > div > div:nth-child(3) > h2:nth-child(8)
${LOCPUFFYPRODUCTRETURNSINFORMATION1}   css=body > div.container.content > div > div:nth-child(3) > p:nth-child(9)
${LOCPUFFYPRODUCTRETURNSINFORMATION2}   css=body > div.container.content > div > div:nth-child(3) > p:nth-child(10)
${LOCPUFFYPRODUCTRETURNSINFORMATION3}   css=body > div.container.content > div > div:nth-child(3) > p:nth-child(11)
${LOCPUFFYPRODUCTRETURNSINFORMATION4}   css=body > div.container.content > div > div:nth-child(3) > p:nth-child(12)
${LOCPUFFYPRODUCTRETURNSINFORMATION5}   css=body > div.container.content > div > div:nth-child(3) > p:nth-child(13)
${LOC101NIGHTSLEEPTRIALHYPERLINK}       css=body > div.container.content > div > div:nth-child(3) > p:nth-child(9) > a
${LOCPUFFYCOMHYPERLINK}                 css=body > div.container.content > div > div:nth-child(3) > p:nth-child(13) > a
${LOCPRODUCTBARTITLE}                   css=body > div.product-bar > div > div > div > h2
${LOCPRODUCTBAR}                        css=.product-bar__inner
${LOCPRODUCTBARICON1}                   css=body > div.product-bar > div > div > div > div.product-bar__content > div:nth-child(1) > div.product-bar__icon
${LOCPRODUCTBARICON1DESC}               css=body > div.product-bar > div > div > div > div.product-bar__content > div:nth-child(1) > div.product-bar__icon-title
${LOCPRODUCTBARARROW}                   css=body > div.product-bar > div > div > div > div.product-bar__content > div.product-bar__box.product-bar__box--arrow > div
${LOCPRODUCTBARICON2}                   css=body > div.product-bar > div > div > div > div.product-bar__content > div:nth-child(3)
${LOCPRODUCTBARICON2DESC}               css=body > div.product-bar > div > div > div > div.product-bar__content > div:nth-child(3) > div.product-bar__icon-title
${LOCPRODUCTBARBOTTOMTEXT}              css=body > div.product-bar > div > div > div > div.product-bar__action > div
${LOCPRODUCTBARCTA}                     css=body > div.product-bar > div > div > div > div.product-bar__action > a
${LOCPUFFYGUARANTEEH2}                  css=body > div.detail-sections > div.block__page > div > div > div > div > h2.RNdesk2 > b
${LOCPUFFYGUARANTEEHEROIMAGE}           css=body > div.detail-sections > div.page-banner.is--left-top > div.page-banner__image > div > img
${LOCPUFFYGUARANTEEPAGEBANNERTITLE}     css=body > div.detail-sections > div.page-banner.is--left-top > div.page-banner__inner > div > h1
${LOCGET100RISKFREEBLOCK}               css=.block__page
${LOCGET100RISKFREETITLE}               css=body > div.detail-sections > div.block__page > div > div > div > div > h2.RNdesk2
${LOCGET100RISKFREETITLEDESC}           css=body > div.detail-sections > div.block__page > div > div > div > div > h2:nth-child(4)
${LOC101NIGHTTRIALUSPIMG}               css=body > div.detail-sections > div.block__page > div > div > div > div > div > div.one-third.column.alpha > h5 > img
${LOCFREESHIPPINGUSPIMG}                css=body > div.detail-sections > div.block__page > div > div > div > div > div > div:nth-child(2) > h5 > img
${LOCLIFETIMEWARRANTYUSPIMG}            css=body > div.detail-sections > div.block__page > div > div > div > div > div > div.one-third.column.omega > h5 > img
${LOC101NIGHTTRIALUSPTITLE}             css=body > div.detail-sections > div.block__page > div > div > div > div > div > div.one-third.column.alpha > h5 > strong > span
${LOCFREESHIPPINGUSPTITLE}              css=body > div.detail-sections > div.block__page > div > div > div > div > div > div:nth-child(2) > h5 > strong > span
${LOCLIFETIMEWARRANTYUSPTITLE}          css=body > div.detail-sections > div.block__page > div > div > div > div > div > div.one-third.column.omega > h5 > strong > span
${LOCPUFFYLIFETIMEWARRANTYTITLE}        css=body > div.detail-sections > div:nth-child(3) > div > div > div > h2
${LOCPUFFYLIFETIMEWARRANTYTITLEDESC}    css=body > div.detail-sections > div:nth-child(3) > div > div > div > div.featured_text.puffy_guarantee_text
${101NIGHTSLEEPTRIALBLOCK}              css=.block__rich_text_and_image.block__1565656478391
${LOC101NIGHTSLEEPTRIALTITLE}           css=body > div.detail-sections > div.block__rich_text_and_image.block__1565656478391 > div > div > div > h2
${LOC101NIGHTSLEEPTRIALP1}              css=body > div.detail-sections > div.block__rich_text_and_image.block__1565656478391 > div > div > div > div.regular_text.puffy_guarantee_text > p:nth-child(1)
${LOC101NIGHTSLEEPTRIALP2}              css=body > div.detail-sections > div.block__rich_text_and_image.block__1565656478391 > div > div > div > div.regular_text.puffy_guarantee_text > p:nth-child(2)
${LOC101NIGHTSLEEPTRIALP3}              css=body > div.detail-sections > div.block__rich_text_and_image.block__1565656478391 > div > div > div > div.regular_text.puffy_guarantee_text > p:nth-child(3)
${LOCL101NIGHTSLEEPTRIALPUFFYLINK}      css=body > div.detail-sections > div.block__rich_text_and_image.block__1565656478391 > div > div > div > div.regular_text.puffy_guarantee_text > p:nth-child(1) > a
${LOCHOMEPAGEH1}                        css=body > div.index-sections > div.hero-area.is--mobile-reversed > div.hero-area__box.hero-area__box--hero-image > div > div.b-hero__inner > div.b-hero__content > h1
${LOCL101NIGHTSLEEPTRIALPUFFYMATTRESSHYPERLINK}         css=body > div.detail-sections > div.block__rich_text_and_image.block__1565656478391 > div > div > div > div.regular_text.puffy_guarantee_text > p:nth-child(2) > a
${LOCCOMPAREPAGEH1}                     css=body > div.compare-page.content > div.compare-page__headline > h1
${LOCAWARDSHEROIMAGE}                   css=body > div.top-banner > div.top-banner__image > div:nth-child(1) > img
${LOCAWARDSPAGEH1}                      css=.top-banner__title
${LOCAWARDSPAGEH1DESC}                  css=.top-banner__desc
${LOCAWARDSPAGERANKEDBEST2021TITLE}     css=.awards-section__title
${LOCAWARDSPAGERANKEDBEST2021DESC}      css=.awards-section__desc